- desktop/index.php
- linux/index.php
- mac/index.php
* Fix typo on linux page
* Add reference to downloading older version Desktop 10.0
* Remove documentation items from mac FAQ and move to help.keyman.com (see keymanapp/help.keyman.com#21)
> Cleanup some of the product pages

- _includes/includes/ui/keyboard-details.php
Fixes #5 
As of Keyman 11, the `keyman://` protocol for installing keyboards is deprecated.
This updates the keyboard search boxes for mobile apps to give .kmp links.
> Update mobile download boxes for .kmp

- _includes/includes/ui/keyboard-details.php
Fixes #31 
Even if a site's PHP is configured to `display_errors`, we'll only show them for debugging purposes on `.local` sites.
> Don't show PHP error on the site

- downloads/archive/index.php
- downloads/archive/legacy-embed.php
- downloads/archive/static-keys.php
When clicking the Buy link in version 8 or 9 of Keyman, users would be taken to a confusing page which talked about support. However many of the pages linked there (e.g. community forum) also had script errors which would come up as errors in Keyman to be reported (e.g. [I2992](https://github.com/sillsdev/keyman-issues/issues/2985#issuecomment-536203051)).
This fix means that the users will be given a little more direction about upgrading to latest Keyman version, or at least can activate with a click on one of the listed activation keys. The fix is targeted to resolve that confusion and hopefully get more people on recent versions of Keyman -- nothing else.
Goes with a corresponding tavultesoft.com PR.
> Avoids script errors when users click Buy link in Keyman 8.0/9.0

- _includes/async/keyboard-download.php
- _includes/includes/servervars.php
- _includes/includes/ui/keyboard-details.php
- keyboards/download.php
- web.config
Part of https://github.com/keymanapp/keyman/issues/2248
Initial work on this feature. This redirects all keyboard downloads through a proxy page to allow for triggering of a rebuild of the bundled installer on demand. As a side benefit, implemented the keyboard analytics.
Still to do:
> Collect analytics on keyboard downloads and trigger build of keyboard bundle when keyboard download is started

- _includes/async/keyboard-download.php
- keyboards/download.php
* The `$_ENV` superglobal was not populated on azure so we did not see the variable. Also renamed and made all caps, probably not necessary but not important.
* The download trigger went to the keyboard id, not the keyboard source path as is required by the build scripts.
> fix: bundled installer trigger was not running

- _includes/includes/ui/keyboard-details.php
The embedded mode of keyboard downloads was subtly broken after the
unbundled installer changes. Instead of using a wrapped link pointing
to keyman:download?..., the browser's default download handler would
be triggered.
Fixes keymanapp/keyman#2332.
> fix: embed downloads are not internal

- _includes/async/keyboard-download.php
Include the keyboard id in the message for the build so it shows in
failed builds and in the comment popup for the build in TeamCity.
> chore: improve build reporting

- _includes/includes/ui/keyboard-details.php
- cdn/dev/css/template.css
This reduces font sizes, removes unnecessary elements, and cleans up
the display of the download boxes on mobile devices. It points directly
to the App Store and Play Store to reduce the number of steps to install
a keyboard into Keyman.
> feat: improve keyboard homepage ux on mobile

- go/web.config
Fixes #56.
Documented at https://github.com/keymanapp/keyman/wiki/Permalinks-for-keyboard-downloads
> feat: Add a permalink for keyboard downloads

- go/web.config
- keyboards/share.php
- web.config
This landing page will redirect to the keyboard home page if the keyboard is found, and otherwise will show information on how to access the keyboard via other means.
Goes together with https://github.com/keymanapp/keyman/pull/2426
> feat: add keyboard share landing page

- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/search.css
- cdn/dev/keyboard-search/search.js
This depends on an API update in keymanapp/api.keyman.com#28.
> fix: hide deprecated keyboards by default

- cdn/dev/css/index.css
- cdn/dev/css/template.css
Fixes #9
Applying the font family `MyanmarWeb` was causing "Krangku" to get squashed
With the fix:
> Disable styling for "Rawang" in download links

- linux/index.php
- mac/index.php
Fixes #68
Update mac features table to include `if()` (except for options forms).
Update: Also clarify `if()` support on Linux
> Add if() to mac/ features

- bookmarklet/install-bookmarklet.js
> fix(bookmarklet): url not escaped correctly

- 13/index.php
Now that Keyman for Linux 13.0.21 Beta is available, add instructions for users to download.
Also updated the feedback link to the community site.
> Update Linux Beta info and link to community site

- index.php
- training/index.php
Registration is closed for the upcoming online Developer workshop, so updating the training page.
> change: remove training registration link

- go/android/web.config
- go/ios/web.config
- keyboards/session.php
For Keyman 14.0, we'll be revamping the keyboard search experience on the mobile apps (embedded views to the https://keyman.com/keyboards search page).
This PR adds some preliminary go/android and go/ios links.
> feat: Add android and ios platforms for keyboard search

- web.config
Many of the featured legacy keyboards have been migrated to basic / release keyboards. I originally intended to only update the link to "rawang" which was recently released in keymanapp/keyboards#1163. So I pulled on that thread...
> Update featured list of keyboards

- cdn/dev/css/template.css
- ipa/index.php
fixes #17.
Note, also fixes /cameroon, /burmese, /tibetan/, /greek. However, /greek includes a complex table that is not very responsive and is a lot more work to fix. Hence leaving bit alone for now.
> fix: ipa page is now responsive

- .editorconfig
- amharic/index.php
- cdn/dev/css/template.css
- tamil/anjal-paangu/index.php
- tamil/index.php
- tamil/isis/index.php
- tamil/new-typewriter/index.php
- tamil/suratha-bamuni/index.php
- tamil/visual-media-modular/index.php
- tamil/visual-media-typewriter/index.php
This change allows to download the keyboards that support Linux on the featured keyboards pages. Previously on Linux only the web option was available.
This change also removes the "Free trial available!" from all the pages that still had it, and fixes a
problem in `.editorconfig`.
> fix(linux): Add Linux to featured keyboards pages

- tamil/index.php
Tamil99 doesn't claim to support Linux, but it was released before
Keyman for Linux was released, so it should work. This change enables
the download for Linux.
This is a follow-up of #99. 
See also https://github.com/keymanapp/keyboards/issues/1235
> fix(linux): Add Linux to featured keyboards page for Tamil

- mac/index.php
Following up on keymanapp/keyman#3251 I wanted to check the bottom of the
https://keyman.com/mac/ page which lists a few of the known Keyman for macOS issues.
The recent cleanup of Keyman project scopes & GitHub labels means the link to mac compatibility issues needs a trailing slash (`mac/`)
> Fix link to mac compatibility issues

- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/search.js
- keyboards/keyboard.php
This will allow Keyman to automatically associate the appropriate language from the package at install time.
Part of solution for keymanapp/keyman#1456.
> feat: add bcp47 tag for embedded downloads

- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/search.css
- cdn/dev/keyboard-search/search.js
For compatibility with pagination, obsolete keyboards are always shown but with red flag by them. The wording on the landing page has also been adjusted accordingly.
> fix: obsolete keyboards in search

- cdn/dev/keyboard-search/search.js
Adds a link to the empty search page for popular keyboards. This has two benefits:
1. Allows users to see the most popular keyboards on the site
2. Provides a basis for search engine indexing (although this depends a bit on how well search engines run js; future possibilities here)
> feat: popular keyboards

- _includes/includes/ui/keyboard-details.php
The keyboard details page will no longer show an Install button or
a Use Online button for deprecated keyboards. While this is forced
on us by technical requirements around package identifier character
use, it also helps to push users to the non-deprecated keyboards,
which is a good outcome.
> chore: disable install pages for deprecated keyboards

- cdn/dev/keyboard-search/install.js
- cdn/dev/keyboard-search/keyboard-details.js
- keyboards/install.php
Adds support for the `keyman:` protocol refresh pattern for Windows install/ processes.
TODO:
> feat: keyman protocol support in install page for Windows

- cdn/dev/keyboard-search/search.js
search.js still had a reference to azurewebsites.net. With the new
staging site scheme we don't need to treat staging sites any
special - they follow the regular pattern.
> chore: Use new staging site for search

- .well-known/apple-app-site-association
Please note the documentation here: https://developer.apple.com/documentation/safariservices/supporting_associated_domains
Apple's file location _and_ name requirements are pretty stringent.  
- Yes, the file uses the JSON format.  
- No, it _must not_ use the .json extension.
- According to older documentation, we _may_ be able to drop the `.well-known` folder component of the URL.
- Any form of redirect leading to the file is not allowed.  The file itself must exist at the specified location, no redirects.
> feat: server-side support for iOS universal links

- .gitignore
- .well-known/assetlinks.json
Cherrypick #143 to master
Following the documentation from https://developer.android.com/training/app-links/verify-site-associations
This adds the assetlinks.json file to keyman.com
* Also updated .gitignore to include dependencies used in the staging branch.
> cherrypick: Add Android app association

- cdn/dev/keyboard-search/search.js
- downloads/archive/index.php
- keyboards/index.php
Added a link into the archive page to give access to obsolete keyboards. By default, they will not be listed.
> fix: skip deprecated keyboards

- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/search.js
- keyboards/index.php
This fixes a script error in search.js which was assuming the existence of certain elements on the page. It didn't make sense to include the script in the detail page anyway.
```
Uncaught TypeError: Cannot read property 'q' of undefined
at init (search.js:282)
at load_search (search.js:311)
```
> fix: don't load search.js on detail page

- cdn/dev/keyboard-search/search.js
While these keyboards were already excluded from the search if the obsolete flag was not set, the presentation did not necessarily put them below the "Obsolete" heading.
Relates to keymanapp/api.keyman.com#87
> fix: non-unicode keyboards are obsolete too

- cdn/dev/keyboard-search/search.css
- cdn/dev/keyboard-search/search.js
- keyboards/index.php
When embedded, only show keyboards for that platform (fixes misnamed parameter).
Also, hides platform icons in search results when embedded.
> fix: filter keyboards for platform

- .github/workflows/ci.yml
Given the failed test https://github.com/keymanapp/keyman.com/pull/143/checks?check_run_id=929928229 I wanted to see what the Khmer link returned, but it was a redirect so that wasn't very helpful for diagnostics!
> chore: ci test change link for khmer

- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/embed.css
- cdn/dev/keyboard-search/search.css
- cdn/dev/keyboard-search/search.js
- keyboards/index.php
Relates to keymanapp/api.keyman.com#87. Windows-based component at keymanapp/keyman#3463.
This shows screenshots for web-based and mockups for embedded iOS/Android (mockups because they are missing the Keyman app frames):
> feat: rework download keyboard dialog style

- cdn/dev/css/template.css
- cdn/dev/js/kmlive.js
Fixes #45. When the keyboard search within the Keyboards menu is focused, moving the mouse can cause the menu to disappear, which is confusing for the user.
> fix: menu disappears with mouse move

- cdn/dev/keyboard-search/search.js
Fixes #125. Older android don't support arrow functions.
> fix: console error on downlevel android

- cdn/dev/keyboard-search/dedicated-landing-pages.js
- cdn/dev/keyboard-search/search.css
- cdn/dev/keyboard-search/search.js
- keyboards/index.php
Fixes #37. Includes matching landing pages at top of keyboard search results. Matches on partial terms.
> feat: add landing pages to results

- cdn/dev/keyboard-search/install.css
- keyboards/install.php
Fixes the layout and links on the keyboard install page for macOS. Does not include any automatic install universal link
patterns. Also fixes wording for Linux page.
Part of #109.
> fix: keyboard install page for macOS

- _includes/includes/ui/keyboard-details.php
I introduced a bug so I could do another 1 character PR. Really not really.
> fix: uasort instead of usort

- keyboards/h/ipa/index.php
The bu keyboard has been migrated to bu_phonetic.
By request on the [community site](https://community.software.sil.org/t/cant-find-how-to-type-ipa-pre-nasalized-superscript-nd-usin-new-keyman/2594/9), this changes the link on the IPA landing page accordingly.
Cherrypick the change from 6bb21bd72556d8acf2de1c49dd7408ce8cf80f02 to staging
> fix: Change IPA link to bu_phonetic

- linux/index.php
https://community.software.sil.org/t/keyman-launch-pad-code-not-working/3920/3
A Linux user reported not being able to install Keyman for Linux on his configuration
> Im using Ubuntu Mate Release 20.04.1 LTS (Focal Fossa) 32 bit
Kernel Linux 5.4.0-1015-raspi armv7l
Mate 1.24.0
This clarifies Keyman for Linux's architecture as amd64.
TODO: copy to help.keyman.com/products/linux
> fix: linux - Clarify architecture

- keyboards/install.php
Relates to keymanapp/api.keyman.com#109.
> feat(android): Android install page

- downloads/pre-release/index.php
This mirrors the work in #187, just for the production site. We only need to change the pre-release page for this update; stable versions of course haven't changed.
> chore: keyman windows installer filename (production)

- keyboards/h/greek/index.php
- keyboards/h/ipa/index.php
While the old links work, they involve an unnecessary redirect and make maintenance harder.
> chore: fixup internal keyboard links

- cdn/dev/keyboard-search/install.js
- keyboards/install.php
Fixes #200.
The clever download pattern we established whereby the protocol handler would be used to start a download, and fallback to an installer if the protocol handler was not present, is broken with Chrome 85. It turns out that this was never explicitly supported, and was just a side-effect, so it's unlikely to return. This makes a marginally less smooth install experience but it should not be a significant issue, just one extra click on first install.
Screenshot of new install page, with Keyman already installed:
If the user does not have Keyman installed, they won't get the popup, and they'll need to click the Download button.
> fix: Chrome 85 breaks our clever download pattern

- .gitignore
- keyboards/install.php
The bundled installer link for Keyman keyboards for Windows was not working if bcp47 was not specified. Furthermore, it would default to the stable setup.exe, which is not correct while we are in alpha or beta for 14.0, as earlier stable versions do not support the custom filename pattern we need.
> fix: install link broken

- downloads/pre-release/index.php
Update instructions how to install pre-release version of keyman. The package name is now `onboard-keyman` instead of `onboard`. Part of keymanapp/keyman#3966.
> feat(linux): Rename onboard package

- downloads/releases/_version_downloads.php
- downloads/releases/web.config
This is a very basic landing page for versioned installs which we can use with keymanapp/keyman#4202. Depends on an update to downloads.keyman.com, coming shortly.
> feat: versioned download pages

- bookmarklet/index.php
- bookmarklet/install-bookmarklet.js
Fixes keymanapp/api.keyman.com#47.
This adds the version parameter to the api call in order to get all keyboards compatible with the current version. Also tidied up global variables for future maintainability.
There has long been a hidden feature which we have not really used, so I will highlight out again here: you can pass in a `keyboard` and `language` parameter into the page to get the page to show just a single keyboard, for example:
https://keyman.com/bookmarklet/?keyboard=tibetan_direct_input&language=adi-tibt
I can see this being useful in a variety of possible situations in the future.
> fix: bookmarklet list missing many keyboards

- cdn/dev/keyboard-search/search.js
Fixes #208.
The initial state of the keyboard search page was not returned when the back button was pressed, unlike subsequent states.
> fix: update search result when Back button pressed

- _includes/includes/ui/keyboard-details.php
Fixes #207.
If a keyboard package result does not include a package, hide the package download link (e.g. `ipauni11`).
> fix: hide package download link where appropriate

- cdn/dev/css/template.css
- keyboards/h/burmese/index.php
- keyboards/h/cameroon/index.php
- keyboards/h/greek/index.php
- keyboards/h/sinhala/index.php
- keyboards/h/tibetan/index.php
- keyboards/h/urdu/index.php
- web.config
Fixes #174 to improve viewing the keyboard landing pages on mobile
Amharic (width of download text)
Cameroon (scale the picture)
Greek (quote)
Urdu (Window screenshot)
> Fix: keyboard landing pages when viewed on mobile

- downloads/_downloads.php
- downloads/archive/index.php
- downloads/releases/_version_downloads.php
- windows/download.php
In prep for releasing to stable:
* Fixes #186 to update Windows installer names
* Add 13.0 stable links to archive page
> chore: Rename Windows download links

- keyboards/h/sinhala/garp/index.php
- keyboards/h/sinhala/sipon/index.php
- keyboards/h/tamil/anjal-paangu/index.php
- keyboards/h/tamil/new-typewriter/index.php
- keyboards/h/tamil/suratha-bamuni/index.php
- keyboards/h/tamil/visual-media-modular/index.php
- keyboards/h/tamil/visual-media-typewriter/index.php
- keyboards/h/urdu/index.php
- web.config
Quite a few of the featured keyboards have since been deprecated.
This updates the keyboard ID's to get the current download links (along with working keymanweb links)
> fix: Update deprecated links for featured keyboards

- 14/webinar.md
This adds a zoom link when it is time for the webinar, opening the link 5
minutes before the webinar starts. I think that makes sense -- or should we make it 15 minutes?
The link will disappear while webinars are not running, to avoid confusion.
> feat: zoom link for webinars

- cdn/dev/keyboard-search/install.js
Fixes #276.
Ensures we don't try the protocol handler for old versions of Firefox, as older versions would try and load the page and break the install experience. Only version 87.0 and later will be supported for the protocol handler (current version as of writing).
> fix: support old versions of Firefox in install page

- developer/features.php
As @bennylin points out on 
https://community.software.sil.org/t/zwsp-in-keyman-14/4582/3
The Keyman Developer 14.0 features page should list adding `*ZWNJ*` instead of `*ZWSP*`
> chore: Fix *ZWNJ* typo

- _includes/includes/ui/keyboard-details.php
- keyboards/install.php
This reduces the issue of web crawlers artificially bumping stats for keyboard package downloads.
Ref: https://ahrefs.com/blog/nofollow-links/
> chore: rel=nofollow for package download links

- _common/KeymanHosts.php
- keyboards/session.php
Groundwork required for Chrome 90+ and SameSite cookies.
Fixes keymanapp/keyman#5193.
Without this, cookies within an iframe in the Download Keyboard dialog will be silently blocked, which causes styling and other aspects of the keyboard search to go wrong, as we use session variables to maintain the embedded state of the keyboard search, per platform.
In order to allow us to test locally, this means we need to upgrade our localhost (keyman.com.local, etc) sites to https. This is a good thing, overall, as it reduces the difference between local dev and live sites slightly further.
> chore: https for dev hosts and secure session for keyboard search

- keyboards/index.php
Fixes keymanapp/keyman#5194.
Because the keyboard search lives inside an iframe when hosted in the Keyman app, we cannot use autofocus. Instead we use a script to do the autofocus at page load.
> fix(windows): auto focus for keyboard search

- _includes/includes/ui/keyboard-details.php
- cdn/dev/css/template.css
- cdn/dev/keyboard-search/install.css
- cdn/dev/keyboard-search/keyboard-details.js
- cdn/dev/keyboard-search/search.css
- keyboards/install.php
* Relates to keymanapp/keyman#5219.
* Goes with keymanapp/keyman#5230.
Add the link for Google Play Install Referrer and reorganise the install page for Android to make the one-step install clear.
Also cleans up a few bits and pieces with the look and feel of the install, fixing a HTML layout error and tweaking some CSS to make the page easier to understand.
Note that the keyboard search box at the top no longer wraps, and the left and right borders have been removed.
> feat(android): Google Play Install Referrer link

- cdn/dev/keyboard-search/search.css
Relates to #309 and 🍒 pick of #311 to `staging`
The CSS keyword [unset](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) is invalid on Chrome 37 (Android 5.0).
This was causing the empty search results not to appear. This PR uses `initial` instead.
> fix: Use css keyword `initial` instead of `unset` 🍒 

- cdn/dev/keyboard-search/search.css
Fixes #309 
The CSS keyword [unset](https://developer.mozilla.org/en-US/docs/Web/CSS/unset) is invalid on Chrome 37 (Android 5.0).
This was causing the empty search results not to appear. This PR uses `initial` instead.
Will need to 🍒 pick to `staging` branch.
> fix: Use css keyword `initial` instead of `unset`

- free/index.php
This fixes the list alignment at the bottom of the `/free` page
Current list on the live site:
> chore: Fix list alignment in `/free`

- cdn/dev/keyboard-search/keyboard-details.js
When a user visits keyman.com in Safari on iPad or iPhone, they can request 'Desktop Mode'. In this situation, keyman.com was returning downloads for macOS instead of for iOS. This patch returns instead the iOS download if it detects a touch screen, which Macs do not support. If a touch-screen Mac is released, we'll have to revisit this.
> fix: give iOS downloads for iOS Safari in desktop mode

- go/download/_download.php
`https://keyman.com/go/download/<prog>`, where prog can be kmcomp, keyman-developer, keyman-windows, or keyman-mac, now supports the optional query string parameter `version`. This, along with query string parameter `tier`, makes a good permanent URL for downloading Keyman binaries (forwards to downloads.keyman.com at present), e.g.
https://keyman.com/download/kmcomp?tier=stable&version=15.0.260
This is used in a variety of locations already. The new functionality will be used by the keyboards repository so that we do not need to embed the binaries in the repository any longer.
Ref keymanapp/keyboards#1883
> chore: add version parameter to download direct link

- windows/keepintouch-100.php
- windows/keepintouch-140.php
Add the `user-select: none;` property for embedded frames for the `keep in touch page` used in Keyman Configuration for windows. Made the same change for the web-hosted version again only if it is `embedded`.
> fix(windows): disable text selection in embeded frames

- fonts/index.php
Fixes #352 
During the change from Keyman 13.0 to 14.0, we migrated the Windows in-app help from php files to Markdown format.
This fixes the broken link.
(Would the CI link checker have flagged this?)
> chore: Fix broken link to font-helper

- keyboards/install.php
Fixes #351 
Similar to the bug in #352, some of the keyman.com cross-site links need to update to the Markdown directory structures on help.keyman.com.
Since the link is for current-version, I don't think we need logic for Keyman 13.0 and earlier.
> chore: Fix broken link to download and install Keyman

- cdn/dev/js/kmlive.js
Relates to keymanapp/keyman#7915.
> fix: override iPad's misreporting of user-agent in desktop mode

- _includes/includes/ui/keyboard-details.php
Relates to keymanapp/keyman#9351.
> chore: remove deprecated field data from keyboard_info usage 🎺

- .gitignore
- .htaccess
- build.sh
- go/.htaccess
- go/download/.htaccess
- test/index.md
More updates for #337
Since the broken link checker doesn't exercise the /go redirects, this PR adds a test page.
Each link also has one for the live keyman.com site so we can manually compare.
> chore: Add test page for /go links 🦭

- _test/go.md
- go/.htaccess
Oops - I built a local Keyman Android app to try to download keyboard packages from keyman-staging and realized I had a few TODO's to handle in /go links
Reference to the missing bits from web.config (currently used on the live site)
https://github.com/keymanapp/keyman.com/blob/ab3d0a4dfcb1915a9dafd10e2d98fff0a90b4d03/go/web.config#L19-L47
* Also updated the _test/go.md test page
> fix: go links for model/keyboards 🦭

- .htaccess
- go/download/.htaccess
Follows #429 
Audited the .htaccess Redirect rules to see if I missed other instances where query string needs to be appended.
https://github.com/keymanapp/keyman.com/blob/ab3d0a4dfcb1915a9dafd10e2d98fff0a90b4d03/web.config#L39-L47
https://github.com/keymanapp/keyman.com/blob/ab3d0a4dfcb1915a9dafd10e2d98fff0a90b4d03/web.config#L59-L62
https://github.com/keymanapp/keyman.com/blob/ab3d0a4dfcb1915a9dafd10e2d98fff0a90b4d03/go/download/web.config#L8-L11
> fix: append query strings for some other redirects

- .htaccess
Fixes #442 reverting redirects to rewrites
Comparison to legacy /downloads/releaeses/web.config rules
```xml
<rule name="releases-tier/download" stopProcessing="true">
<match url="^(alpha|beta|stable)/(.+)$" />
<action type="Rewrite" url="_version_downloads.php?tier={R:1}&amp;version={R:2}" />
</rule>
<rule name="releases-download" stopProcessing="true">
<match url="^(.+)$" />
<action type="Rewrite" url="_version_downloads.php?version={R:1}" />
</rule>
<rule name="index" stopProcessing="true">
<match url="^$" />
<action type="Redirect" url=".." />
</rule>
```
> fix: Rewrite instead of redirect /downloads/releases

- cdn/dev/css/index.css
Addresses the styling issue @mcdurdin reported
> fix: h1 styling for mobile layout

- bookmarklet/index.php
- cdn/dev/css/index.css
- cdn/dev/css/template.css
> chore: correct <li> styling and make bookmarklet search box responsive

- build.sh
Update BOOSTRAP_VERSION to 0.8 to incorporate fix from keymanapp/shared-sites#20
> chore: Update BOOSTRAP_VERSION to 0.8

- _includes/2020/templates/Foot.php
- about/index.md
- contact/index.php
- ldml/index.md
- package.json
Related to #463 
Reflects the name change from "SIL International" to "SIL Global" as of August 2024 from
https://www.sil.org/about/news/new-name-90-sil-international-becomes-sil-global
Not changing historical pages
> chore: Use new SIL Global name

- cdn/dev/css/template.css
- downloads/all-version/index.php
- downloads/index.php
- downloads/releases/_version_downloads.php
fixes: https://github.com/keymanapp/keyman.com/issues/392
> feat: add 'prev' and 'next' version navigation to downloads/releases

- build.sh
- resources/init-container.sh
Fixes #470 to skip generating CDN if `./build.sh --debug`
Since this is changing `BOOTSTRAP_VERSION` to `chore/v0.10`, I'm unsure if we want to merge this to master. Or have a separate branch while the Logo work is in flux...
(edit)
BOOSTRAP_VERSION v0.10 is published so updating PR to use that.
> fix: Skip CDN for --debug builds

- resources/init-container.sh
Follows #471 and mirrors keymanapp/help.keyman.com@5a99378654b42bc88ccc4cc3dbc889cdc409da7b
of removing /cdn/deploy if it exists (e.g. from a previous run)
> fix: clean CDN cache on --debug

- _includes/2020/templates/Menu.php
- _includes/includes/ui/download-links.php
- index.php
Addresses the point on #383
> Use good alternative descriptions (alt attributes) for your images
This adds alt attributes for main page images.
(Not including shared-sites logos)
> chore: Add img alt descriptions for main page

- .github/workflows/ci.yml
- build.sh
- composer.json
/donate redirects to another site that gives a 403 forbidden response to bots, which breaks the link checker. So just exclude it.
Fixes: #488
> fix: exclude /donate from broken link checker

- testimonials/index.md
I noticed the bottom of the testimonial page didn't render because of a missing `</p>` tag.
> fix missing closing tag on testimonial page

- _includes/2020/templates/Head.php
- _includes/includes/md/mdhost.php
- _includes/includes/template.php
- build.sh
In preparation for #383 and depends on keymanapp/shared-sites#34 in handling optional page description fields that can be written to the HTML header.
**Note**: CI Link checker fails until keymanapp/shared-sites#34 gets merged into chore/v0.11
This can be seen in the page sources of the various `/_test/` Markdown pages since they already include 
```yml
---
title: ...
description: ...
---
```
An example of a page without a description is
`/14/keyman-engine-changes`
> feat: Add metadata description content to headers 📓

- _includes/2020/templates/Head.php
Addresses this point of #383 
> Fix errors regarding the language markup of your webpage
The language is not specified in the HTML markup
We're not yet ready to localize keyman.com, so for now setting the HTMl lang tag to "en".
> fix: Specify HTML lang tag "en" 📓

- keyboards/h/amharic/index.php
- keyboards/h/ipa/index.php
- keyboards/h/tigrigna/eritrean.php
- keyboards/h/tigrigna/index.php
Follows #489 for #383
This adds HTML lang tags for dedicated keyboard landing page examples. Some of the landing pages already contained lang tags.
Also, on the IPA landing page, using `und-fonipa` (even though the keyboard currently uses und-Latn)
Tagging @dyacob for checking the Amharic, Ethiopic, and Eritrea examples
> fix: Add HTML lang tags for dedicated keyboard landing page examples 📓

- android/index.php
- downloads/archive/index.php
- downloads/index.php
- downloads/pre-release/index.php
- index.php
- iphone-and-ipad/index.php
- keyboards/index.php
- linux/index.php
- mac/index.php
- windows/download.php
- windows/features.php
- windows/index.php
Support for #383, follows  #485
This adds metadata descriptions for the major pages on keyman.com
> feat: Add descriptions for major pages 📓

- _includes/2020/templates/Head.php
- _includes/includes/template.php
Follows #489 fixes #496 and fixes KEYMAN-COM-1CX
where `$fields->language` was undefined.
This also propagates the optional header `language` if it's set. I would expect most pages fallback to `en`
https://github.com/keymanapp/keyman.com/blob/64bfdfdeefa45c94d0e8915b174a24141ea70c7b/_includes/2020/templates/Head.php#L16-L18
> fix: Handle optional `language` tag in header

- keyboards/h/amharic/index.php
- keyboards/h/burmese/index.php
- keyboards/h/cameroon/index.php
- keyboards/h/greek/index.php
- keyboards/h/ipa/index.php
- keyboards/h/sinhala/garp/index.php
- keyboards/h/sinhala/sipon/index.php
- keyboards/h/tamil/anjal-paangu/index.php
- keyboards/h/tamil/index.php
- keyboards/h/tamil/isis/index.php
- keyboards/h/tamil/new-typewriter/index.php
- keyboards/h/tamil/suratha-bamuni/index.php
- keyboards/h/tamil/visual-media-modular/index.php
- keyboards/h/tamil/visual-media-typewriter/index.php
- keyboards/h/tibetan/index.php
- keyboards/h/tigrigna/eritrean.php
- keyboards/h/tigrigna/index.php
- keyboards/h/urdu/index.php
Addresses part of #383
Follows #486 for adding metadata descriptions to the dedicated keyboard landing pages.
> fix: Add descriptions for dedicated keyboard landing pages

- _includes/2020/KeymanWebHost.php
- _includes/includes/ui/keyboard-details.php
- cdn/dev/keyboard-search/search.css
- developer/keymanweb/index.php
From Chiang Mai Hackathon.
Notes:
1. Only shows on Windows, macOS, and Linux.
2. Does not show if no web keyboard available.
3. Does not show if keyboard is deprecated.
4. Does not show if search is embedded in app (keyboard install flow)
5. Uses as-yet undocumented osk-host pattern for KMW. (TODO)
6. Hacks away wrong `z-index: 10000` leaking into hosted osk from KMW. (TODO)
> feat: show keyboard preview in keyboard details

- _includes/includes/ui/keyboard-details.php
I was testing #502 locally and saw this PHP error on
http://keyman.com.localhost/keyboards/sil_ipa
This adds a check for `languageName` before printing them in keyboard details.
> fix: Check languageName exists before printing in keyboard details

- Dockerfile
- _includes/locale/README.md
- _includes/locale/en/LC_MESSAGES/.gitignore
- resources/init-container.sh
Some prep work towards #384 of localizing the keyboard search
This brings in the Dockerfile updates from #500 to set up the en_US locale and install the PHP gettext.
The locale/README.md is just capturing an initial setup and will be refined in future PR's.
The .po localization files will also be added on separate PR's and reside in /_includes/locale/en/LC_MESSAGES/
> feat: Configure `en_US` locale in Dockerfile 📡

- resources/init-container.sh
Missed this line in #517 to restore the path when init-container.sh is done
> fix: restore path in init-container.sh 📡

- developer/authoring-services.md
- developer/index.php
Relates to a discussion on a forum:
https://community.software.sil.org/t/keyman-keyboard-creator-directory/9408/5
Once we get a name or two, we'll publish.
Form responses at: https://docs.google.com/forms/d/1bb42Gs09z6iqJf_ub63o9tEoOS27Rx_7omPPzfH3Mk0/edit#responses
> feat: keyboard authoring service directory

- _includes/includes/template.php
- _includes/locale/Locale.php
- _includes/locale/README.md
- keyboards/index.php
- keyboards/session.php
Continues #384
This starts a Locale.php class which will expand to handle pointing to the localized.po files.
For now, it allows the current locale to be set with a query parameter like `lang=fr-FR` (previously was `locale`)
And confirmed with test code on keyboards/index.php
```php
<li>Current locale is <?= Locale::currentLocale() ?></li>      
```
> feat: Add Locale.php class to set current locale 📡

- iphone-and-ipad/index.php
Part of: #415.
There is no documentation from the `$stable_version` so I am adding a `/` to ensure the dropdown of other available versions.
Before:
After:
This PR is ready for review.
> fix: links to Keyman engine content

- _includes/includes/ui/keyboard-details.php
Ensures that the keymanweb keyboard reference is correct for the package, as it will not always match the package identifier, or may not be available as a standalone keyboard. This then prevents the error in #525 from presenting.
This fix works around a data issue documented in keymanapp/keyman#12853.
I also cleaned up some of the confusion between package id and keyboard id -- but there are deeper ambiguities still present w.r.t package/keyboard id here which we may just need to live with.
Fixes: #525
Relates-to: keymanapp/keyman#12853
> fix: avoid error when jsFilename is missing or mismatches package id

- .htaccess
I believe this addresses keymanapp/keyman#12797
In Keyman for Android, the language search for keyboards wasn't shown in an embedded search
https://keyman.com/keyboards/languages/en?embed=android&embed_version=18.0
This updates .htaccess to preserve the [query string](https://httpd.apache.org/docs/current/rewrite/flags.html#flag_qsa)
http://keyman.com.localhost/keyboards/languages/en?embed=android&embed_version=18.0
> fix: Append query string for /keyboards/languages searches

- _includes/locale/Locale.php
- _includes/locale/README.md
- _includes/locale/en/LC_MESSAGES/keyboards-en.po
- _includes/locale/en/LC_MESSAGES/keyboards-es-ES.po
- _includes/locale/en/LC_MESSAGES/keyboards-fr-FR.po
- keyboards/index.php
Re-implements #500 for #384
This updates Locale.php for localizing the keyboards/ index page
* Validate the new locale before overriding the current locale
* `setTextDomain()` to manage the localization files
* Add `_s()` wrapper
* Use the pattern described in #384 of storing the localized strings into an array
Note: the "Search" button image asset contains English text.
**French**
http://keyman.com.localhost/keyboards/?lang=fr-FR
**Spanish**
http://keyman.com.localhost/keyboards/?lang=es-ES
> feat: Localize keyboards index page 📡

- build.sh
Update shared-sites to v0.15 notably:
* Adds GFM-style alerts
* Fix BASH syntax in docker.inc.sh
> chore: Update shared-sites to v0.15

- about/developers/index.md
I remember @mcdurdin mentioned adding a section to the about/developer page so I waited until graduating. I could not find that message now but I hope this is the correct place to add.
This PR is ready for review.
Thank you!
> chore: add a section to `about/developers`

- 12/index.php
- 13/index.php
- 14/index.php
- _control/info.php
- _ie_thunk/search.php
- _includes/2020/KeymanDownloadVersions.php
- _includes/2020/KeymanWebHost.php
- _includes/includes/servervars.php
- _includes/includes/ui/downloads.php
- _includes/includes/ui/keyboard-details.php
- _includes/includes/ui/legacy-keyboard-details.php
- _legacy/keyboards/download.php
- _legacy/keyboards/keyboard.json.php
- _legacy/keyboards/keyboard.php
- _legacy/keyboards/share.php
- android/index.php
- build.sh
- developer/keymanweb/keyboards.php
- developer/keymanweb/keymanweb-version.inc.php
- downloads/all-versions/index.php
- downloads/index.php
- downloads/pre-release/index.php
- downloads/releases/_version_downloads.php
- go/download/_download.php
- go/package/download.php
- iphone-and-ipad/index.php
- keyboards/install.php
- keyboards/keyboard.json.php
- keyboards/keyboard.php
- keyboards/share.php
* Splits the server-side and client-side references to keyman sites so that docker-based PHP can reference host.docker.internal on development machines for cross-references.
* Removes all remaining usage of global `$KeymanHost` variable, instead using `KeymanHost::Instance()` for consistency.
* Removes some links to legacy sites such as sentry.keyman.com.
Relates-to: keymanapp/shared-sites#53
> refactor: clean up KeymanHosts usage and make consistent

- developer/keymanweb/sample2.php
This change modifies demo2 and removes languages from the list that don't provide a web keyboard. Also reword the placeholder text to make it clearer that it's only a selection of languages.
Fixes: #561
> fix: remove languages without keyboard and reword placeholder in demo2

- _includes/2020/Util.php
While investigating some Sentry issues on keyman.com, I noticed keyman-staging was using `dev` instead of `deploy` on the CDN assets
https://keyman.sentry.io/issues/6400178766/?environment=staging&project=5983516
This will make it to `staging` branch at the end of the sprint-merge
> fix: Use CDN on staging site

- cdn/dev/keyboard-search/search.css
Some keyboards use `&KMWHelpFile` to present a HTML fragment instead of the normal KeymanWeb OSK. Those keyboards were not displaying correctly in this view, with the content overlapping the Keyboard Details area.
Allowing the `#osk-host` element to grow mitigates this, although there are still keyboards such as https://keyman.com/keyboards/sil_ipa that do not have an optimal presentation.
Fixes: #573
> fix: allow #osk-host element to grow in keyboard details

- downloads/archive/index.php
With the upcoming stable-18.0 release, this adds stable-17.0 links to the downloads/archive page.
re: kmcomp download archive
Do we need to keep 16.0 links, or just the latest stable?
> chore: Add stable-17.0 links to downloads/archive

- keyboards/install.php
Fixes #607
This fixes the iOS and Linux links for installing a keyboard. The links for other platforms are working.
* **TEST_LINKS**  - Verifies new links work
1. Append each of the new links on the PR to https://help.keyman.com/
2. Verify each link is valid
> fix: help links on installing keyboards
