keymanapp/keyman.com

desktop/download.php
The header has a form with the same field names. This breaks the Javascript in the submit onclick action.
=> [keyman.com] Fix broken download form

developer/download.php
=> [keyman.com] Add note for kmcomp in download page

developer/keymanweb/keyboards.php
Addresses issue raised at https://github.com/keymanapp/keyboards/issues/611#issuecomment-484230335
=> [keyman.com] Use current stable version for keyboards list for keymanweb

android/app/web.config, go/desktop/10.0/web.config, go/desktop/11.0/web.config, go/developer/10.0/web.config, go/developer/11.0/web.config, go/linux/11.0/web.config, go/macos/10.0/download-keyboards/web.config, go/macos/11.0/download-keyboards/web.config, go/web.config
=> [keyman.com] After recent changes to root web.config, some redirect rules were failing to apply.

developer/keymanweb/index.php, developer/keymanweb/sample1.php
This updates the keyman.com/developer/keymanweb section.
=> Web 12.0 info prep

web.config
=> Updates Dinka link to latest version of keyboard.

_includes/includes/phone-menu.php, _includes/includes/top-menu.php, cdn/dev/css/index.css, index.php, training/index.php
Links to pre-registration form, will need to be refreshed
once we have a full registration form up.
=> feat: training home page

training/index.php
Now have a live training link.
=> feat: full registration link

desktop/keepintouch-100.php
Missed this on the previous PR.
=> fix: link to keepintouch

13/index.php, _includes/includes/servervars.php, index.php
Start staging content for Keyman 13.0 stable release
=> Initial seed for staging 13.0 content

android/index.php
Add feature content for Keyman for Android 13.0
=> feat(android): Add 13.0 feature list

13/index.php, linux/index.php
* Update 13.0 announcement for simpler macOS installation
* Update linux feature table (now handles keyboard options form)
=> Minor edits for mac and linux

privacy/index.php
Addresses  #41  for updating link to SIL's privacy policy on keyman.com
=> Update link to SIL privacy policy

privacy/index.php, web.config
From review comment of #83 
> Can we turn this into a web.config please? Trying to eliminate use of pure redirects in PHP for future maintenance.
=> Move privacy redirect to web.config

downloads/_downloads.php, linux/download.php, linux/index.php
While I was validating the Keyman for Linux 13.0.103 release, I realized I needed to install ibus-keyman.
I would have expected it to be included in the keyman package...
=> update linux installation instructions

mac/index.php
Goes with keymanapp/help.keyman.com#131
Update the link for installing Keyman 13 for macOS
=> Update link for installing Keyman for macOS

cdn/dev/css/template.css, cdn/dev/js/kmlive.js
Fixes #3.
Previously, they were non-clickable on desktop devices. Now they are handy and clickable.
=> fix: hamburgers are now edible on the desktop

go/desktop/web.config, go/web.config
This is the keyman.com side of changes from keymanapp/keyman#2875
=> feat: new endpoints for Keyman Desktop / Sentry

engine/index.php
=> feat: add reference to KAB

cdn/dev/js/kmlive.js
There was still a piece missing to allow to download from Linux.
=> fix(linux): Fix download on Linux from featured keyboards pages

testimonials/index.php
Gathered some testimonials from the Keyman Twitter feed.
We don't render Twitter emojis though
=> add more testimonials

cdn/dev/keyboard-search/search.js
Now supports highlighting any type of term supported by keyboard search.
=> feat: highlight more search terms

_includes/includes/ui/keyboard-details.php, cdn/dev/keyboard-search/search.css, cdn/dev/keyboard-search/search.js, keyboards/index.php
Also, fix a couple of bugs in search javascript; some of these
globals will be improved in a future PR, so this is just patching
to get it working for now.
=> feat: show language codes in keyboard detail

index.php
Coinciding with the [PSA](https://community.software.sil.org/t/looking-for-testers-keyboard-search-refresh/3570) looking for testers of the new keyboard search,
this PR updates the frontpage banner on the staging site to announce the keyboard search.
=> chore: Chance announcement to new keyboard search

cdn/dev/css/template.css, cdn/dev/js/kmlive.js
=> fix: phone menu visibility weird on responsive size

_includes/includes/ui/keyboard-details.php, go/desktop/web.config, go/windows/web.config
This goes with keymanapp/keyman#3325
=> feat: define go/windows paths

.github/workflows/ci.yml, _includes/includes/servervars.php
Replaces #96 with common Sentry pattern.
=> feat: sentry integration

_common/JsonApiFailure.php, _includes/2020/KeymanComSentry.php, _includes/autoload.php, _includes/includes/servervars.php, go/package/download.php
=> fix: add error codes for go/package/download

cdn/dev/keyboard-search/search.js
=> fix: hide page statistics when few results

cdn/dev/keyboard-search/search.css, cdn/dev/keyboard-search/search.js, keyboards/index.php
* Search history is maintained more reliably now.
* Space is no longer trimmed while typing.
* Hints are shown when no search has been entered.
=> fix: search history and hints

cdn/dev/keyboard-search/search.js, downloads/archive/index.php, keyboards/index.php
Also fixes the last space being deleted during input.
Release to keymanapp/api.keyman.com#87.
=> fix: strip common words from search

about/get-involved.php
This adds content to the staging site on getting involved with localization.
=> modify: Add translate.keyman.com to get-involved

go/package/download.php, go/web.config
=> feat: add model support to /go/package/download

_includes/includes/ui/keyboard-details.php
=> fix: make obsolete banner visible at correct time

_common/KeymanSentry.php, go/package/download.php
Fixes #167. (Also tweaks stats reporting for downloads)
=> fix(common): staging for sentry

_includes/includes/ui/keyboard-details.php, cdn/dev/keyboard-search/search.css
Fixes #176 (was keymanapp/keyman 3599).
=> fix: add links to keyboard details

cdn/dev/keyboard-search/search.js
Fixes keymanapp/api.keyman.com#107.
1. initial load of page does a redirect.
2. urls formed by getCurrentPath not as clean as they should be.
3. short text searches could be cancelled if enter pressed quickly.
4. minor refactoring and cleanup.
=> fix: minor bugs in search

cdn/dev/keyboard-search/install.css, cdn/dev/keyboard-search/search.css, keyboards/install.php
Relates to keymanapp/api.keyman.com#109
iPhone 5 size:
iPad:
=> feat(ios): install page

.github/workflows/ci.yml, cdn/dev/keyboard-search/install.css, cdn/dev/keyboard-search/search.css, keyboards/install.php
Fixes #180.
This copies the same solution as we had in help.keyman.com
=> chore/collect php error.log in ci

_includes/2020/KeymanDownloadVersions.php, _includes/includes/ui/downloads.php, desktop/download.php, downloads/_downloads.php, downloads/pre-release/index.php
=> chore: update keyman windows installer filenames

amharic/index.php, tigrigna/eritrean.php, tigrigna/index.php
These changes were made at the request of @dyacob.
=> [amharic] Update links for Gurage/Sebatbeit Blin and Geez keyboards

cdn/dev/keyboard-search/search.js
Fixes #190.
Pagination was not working after page 5.
=> fix: broken pagination after page 5

_includes/includes/ui/keyboard-details.php, cdn/dev/keyboard-search/search.css
This resolves the errors reported in the broken link check...
=> fix: broken keyboard links

cdn/dev/keyboard-search/search.js
Fixes keymanapp/keyman#3951.
Support old versions of Chrome on older Android devices in keyboard search.
=> fix: array.prototype.find polyfill

_includes/includes/ui/keyboard-details.php
=> fix: monthly download stats on keyboard detail page

14/index.php, downloads/pre-release/index.php
Also update release notes (there are no packages for Fedora yet) and modernize installation command.
=> feat(linux): Fix name of beta ppa

14/index.php, downloads/pre-release/index.php
We now have dedicated beta and alpha ppas.
=> chore(linux): Rename ppas

bookmarklet/index.php, bookmarklet/install-bookmarklet.js, cdn/dev/css/template.css
Fixes keymanapp/api.keyman.com#46 and throws in a spinner on load.
=> fix: use full BCP 47 code for bookmarklet

bookmarklet/index.php, bookmarklet/install-bookmarklet.js, cdn/dev/css/template.css
Makes the bookmarklet list searchable because it is way long... oh, and tweaks the UI slightly, to make it slightly wider and less wasted real estate.
=> feat: bookmarklet search

bookmarklet/index.php, bookmarklet/install-bookmarklet.js, cdn/dev/css/template.css
Cherry-pick of #233, #234, #235.
=> fix: bookmarklet fixes for production 🍒

keyboards/index.php
=> fix: add examples for the search hints

_includes/2020/templates/Head.php, cdn/dev/css/template.css, keyboards/index.php
Fixes keymanapp/keyman.com#206.
* Tweaks link for popularity results
* Adds link for alphabetical results
Side fixes:
* Cleanup of dot point formatting
* Hide staging site from search engines
=> feat: popularity and alphabetical searches

about/index.php, android/index.php, iphone-and-ipad/index.php, testimonials/index.php
* Add what's new in Keyman for iPhone and iPad
* Other minor edits
=> chore: Update minor content

linux/download.php
- mention that Debian contains older Keyman version
=> chore(linux): Update download instructions

_includes/2020/templates/Menu.php, _includes/includes/desktop-features.php, index.php, linux/index.php, mac/index.php, windows/index.php
Based on 2021 Keyman keyboard stats
=> chore: Update site to 2000+ languages

_includes/2020/templates/Foot.php, linux/index.php
=> fix: links to help and blog

14/webinar.md
=> feat: calendar links for webinars

keyboards/index.php
=> fix: use cdn versions of stylesheets etc in keyboard search

14/index.php, linux/download.php, linux/index.php
- fix some formatting
- add installation from pso to more places
- wrap pso command line to fit without scrolling
=> chore(linux): Enhance documentation

_includes/includes/template.php, keyboards/h/sinhala/index.php
Fixes #278.
Fixes KEYMAN-COM-A
=> fix: handle missing user agent

uninstall/index.php
Fixes #279.
Fixes KEYMAN-COM-3Q.
Fixes KEYMAN-COM-3P.
=> fix: handle missing uninstall parameters

14/webinar.md
The final video is still processing so will merge this once that is done.
=> chore: more webinar videos

developer/features.php
* Add keyboards can also be run on Linux
* Add link to lexical-model repo
=> chore: Tweak developer/features page

cdn/dev/keyboard-search/search.js
Fixes [KEYMAN-COM-67](https://sentry.keyman.com/organizations/keyman/issues/4738) for various browsers.
=> fix: includes polyfill

_includes/includes/ui/keyboard-details.php, go/package/download.php
Relates to #297.
Related PRs:
* keymanapp/api.keyman.com#151
* keymanapp/keyman.com#298
* keymanapp/help.keyman.com#389
=> fix: new download statistics

_includes/2020/templates/Head.php
Correlates to keymanapp/help.keyman.com#448.
=> fix: link checker was skipping all links

15/index.php, _includes/2020/KeymanVersion.php, index.php, web.config
=> chore: Start prep for 15.0 Beta announcement

_common/MarkdownHost.php, _includes/2020/KeymanVersion.php, android/index.php, developer/index.php, iphone-and-ipad/index.php, linux/index.php, mac/index.php, windows/index.php
Note: MarkdownHost.php change is just making file identical with other
sites.
=> chore: move to 16.0 beta

bookmarklet/index.php, bookmarklet/install-bookmarklet.js, cdn/dev/css/template.css
One of three PRs fixing https://github.com/keymanapp/keyman/issues/4785.
Note that this relies upon https://github.com/keymanapp/r.keymanweb.com/pull/7, one of the other two PRs contributing to the fix.
=> change: uses centralized bookmarklet implementation 🔖

.well-known/security.txt
Have opted not to include a public key at this time, as that needs more administration to share with the responders to the email address.
=> chore: basic security.txt

.well-known/security.txt, _common/MarkdownHost.php, _includes/2020/KeymanVersion.php, android/index.php, bookmarklet/index.php, bookmarklet/install-bookmarklet.js, cdn/dev/css/index.css, cdn/dev/css/template.css, cdn/dev/js/kmlive.js, developer/index.php, fonts/index.php, index.php, iphone-and-ipad/index.php, keyboards/install.php, linux/index.php, mac/index.php, testimonials/index.php, windows/index.php, windows/keepintouch-100.php, windows/keepintouch-140.php
=> chore: Merge master from Sprint a17s2 to staging

_includes/includes/ui/keyboard-details.php
=> fix: keyboard page was returning incorrect statistics

composer.lock
=> chore: Merge master branch of Sprint A17S12 to staging

go/package/download.php
Fixes [KEYMAN-COM-PR](https://keyman.sentry.io/issues/4244115144).
=> fix: Sentry:KEYMAN-COM-PR

keyboards/h/amharic/index.php, keyboards/h/tigrigna/eritrean.php, keyboards/h/tigrigna/index.php
I won't have time to update these properly for several weeks so I went ahead and did a quick update for just the keyboards. The graphics for the fonts could be reviewed at a later time.
This, at least, removes links to deprecated keyboards and adds links for new keyboards.
Closes [#2259](https://github.com/keymanapp/keyboards/issues/2259)
=> [amharic_tigrigna] Quick update to files

.github/workflows/ci.yml, Dockerfile, _common/KeymanHosts.php, build.sh, composer.json, composer.lock
Updates ci.yml from running IIS to Docker and run tests.
Also updates composer.json and composer.lock to match help.keyman.com
Not incorporating shared-sites on this PR
=> chore: Update CI GHA to run with Docker 🦭

.htaccess, _legacy/.htaccess, archive/.htaccess, go/desktop/.htaccess, go/developer/.htaccess
Addresses the permanent redirect TODO's in #337 
Corresponds to web.config [redirectType="Permanent"](https://github.com/search?q=repo%3Akeymanapp%2Fkeyman.com%20redirectType%3D%22Permanent%22&type=code)
=> fix: Add 301 permanent redirects 🦭

.gitattributes, build.sh, cdn/cdnrefresh.php, resources/init-container.sh
Continuing #337
* Fix cdn pathing for Docker container
* Generate CDN in init-container.sh
=> chore: Generate CDN in init-container.sh 🦭

README.md
Trivial change to trigger webhook
=> chore: Update readme to trigger webhook

_includes/2020/KeymanVersion.php
Note: this file KeymanVersion.php is a prime candidate to be moved to shared-sites as a future task.
=> chore: move to 17.0 beta

cdn/dev/css/feature-template.css, developer/features.php
This should look good on mobile devices. 
Please suggest any changes.
Issue - #432
=> task: update styles for the mobile layout of developer/features

developer/keymanweb/index.php
=> fix: https only docs

developer/keymanweb/index.php
=> fix: remove version from js

about/get-involved.md, jobs/index.md
=> feat: add /jobs page

developer/keymanweb/index.php, developer/keymanweb/keymanweb-version.inc.php, developer/keymanweb/sample1.php, developer/keymanweb/sample2.php
Many thanks to @linuxguist. The sample provided has been lightly modified to match KeymanWeb API usage.
Fixes: keymanapp/help.keyman.com#1357
=> feat: add KeymanWeb sample from contributor @linuxguist

about/developers/index.md
Add short bio in the about developer team for Ross Cruickshank.
Fixes https://github.com/keymanapp/keyman.com/issues/435
=> chore: add short bio for ross

about/developers/index.md
=> chore: add ross link to avatar

keyboards/h/amharic/index.php, keyboards/h/burmese/index.php, keyboards/h/cameroon/index.php, keyboards/h/greek/index.php, keyboards/h/ipa/index.php, keyboards/h/sinhala/garp/index.php, keyboards/h/sinhala/sipon/index.php, keyboards/h/tamil/anjal-paangu/index.php, keyboards/h/tamil/index.php, keyboards/h/tamil/isis/index.php, keyboards/h/tamil/new-typewriter/index.php, keyboards/h/tamil/suratha-bamuni/index.php, keyboards/h/tamil/visual-media-modular/index.php, keyboards/h/tamil/visual-media-typewriter/index.php, keyboards/h/tibetan/index.php, keyboards/h/tigrigna/eritrean.php, keyboards/h/tigrigna/index.php, keyboards/h/urdu/index.php
Also promotes h2 to h1 where needed.
Fixes: #507
=> feat: include 'Keyboard' in title for featured keyboards

_includes/includes/ui/keyboard-details.php
Fixes: #512
Fixes: KEYMAN-COM-1EJ
=> fix: use property_exists instead of array_key_exists

jobs/index.md
Tweaks the /jobs to include part-time volunteers
=> chore: Include part-time volunteers on /jobs

_includes/includes/ui/keyboard-details.php, cdn/dev/keyboard-search/search.css, go/developer/.htaccess, keyboards/session.php
Relates-to: keymanapp/keyman#13073
=> feat(developer): support search for keyboards for TIKE project clone

developer/keymanweb/index.php
=> fix: use KeymanWebHost::getKeymanWebUrlBase instead of $build global

.htaccess, ldml/index.md
Also adds a redirect from /cldr -> /ldml
Fixes: #540
=> chore: update LDML page with current status as of Feb 2025

contact/index.php
chore: Update the Contact page Postal address to include city, ZIP+4, and move country to next line.
Ideally, we'd migrate the .php to .md, but the contact page has embedded PHP code too.
=> chore: Tweak Postal address

.github/workflows/ci.yml
=> chore: Update ci.yml to ubunutu-latest

about/developers/index.md
=> chore: a minor edit of about-mengheng

about/developers/index.md
=> chore: Merge master to staging for Sprint B18S4

about/developers/index.md, developer/keymanweb/sample2.php
=> chore: Merge master to staging for Sprint B18S5

.github/multi-labeler.yml, .github/workflows/labeler.yml
End of sprint task
Test-bot: skip
=> chore: Merge master to staging for Sprint A19S9

build.sh
Update BOOTSTRAP_VERSION to [v1.0.5](https://github.com/keymanapp/shared-sites/releases/tag/v1.0.5).
=> auto: update shared-sites version to v1.0.5
